\include scripts/macros.script

\centerline {My Lame Gym Workout}

\vskip 50

\centerline {Week of ________}

\vskip 40

\set cgap 12
\set sgap 5

\halign {
#\hskip\cgap\hfil&#\hskip\cgap\hfil&#\hskip\cgap\hfil&#\hfil\cr
&Monday&Wednesday&Friday\cr
Bench press&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Peck deck&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Overhead press&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Bent-over raises&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Barbell curls&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Triceps extensions&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Squats&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Deadlifts&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Barbell rows&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Lat pulldowns&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Leg curls&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Leg extensions&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____\cr
Crunches&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____&____\hskip\sgap ____\hskip\sgap ____
}

\vfill
