\include scripts/macros.script

\set hoffset 36
\set voffset 36
\set hsize 540
\set vsize 720

{\font rubik-wet-paint 32 regular \centerline {The Gym Workout}}

\vskip 50

\centerline {Week of ___________}

\vskip 50

\set cgap 20
\set sgap 5

\def sets {__________}
\def exercise {\sets&\sets&\sets}

\centerline{\vbox\halign {
#\hskip\cgap\hfil&#\hskip\cgap\hfil&#\hskip\cgap\hfil&#\hfil\cr
&\hfil\underline{\hbox{\font noto 18 regular Mon}}&\hfil\underline{\hbox{\font noto 18 regular Wed}}&\hfil\underline{\hbox{\font noto 18 regular Fri}}\cr
\noalign{\vskip 16\underline{\hbox{\font noto 16 regular Chest/Arms/Shoulders}}\vskip 10}
Bench press&\exercise\cr
Overhead press&\exercise\cr
Bent-over raises&\exercise\cr
Barbell curls&\exercise\cr
Triceps extensions&\exercise\cr
Dipps&\exercise\cr
\noalign{\vskip 16\underline{\hbox{\font noto 16 regular Legs/Back}}\vskip 10}
Squats&\exercise\cr
Deadlifts&\exercise\cr
Barbell rows&\exercise\cr
Lat pulldowns&\exercise
}}

\vfill
