\include scripts/macros.script

{\font nosifer 30 regular \centerline {The Gym Workout}}

\vskip 50

\centerline {Week of ___________}

\vskip 40

\set cgap 12
\set sgap 5

\def sets {____\hskip\sgap ____\hskip\sgap ____\hskip\sgap ____}
\def exercise {\sets&\sets&\sets}

\halign {
#\hskip\cgap\hfil&#\hskip\cgap\hfil&#\hskip\cgap\hfil&#\hfil\cr
&\hfil\underline{Monday}&\hfil\underline{Wednesday}&\hfil\underline{Friday}\cr
Bench press&\exercise\cr
Peck deck&\exercise\cr
Overhead press&\exercise\cr
Bent-over raises&\exercise\cr
Barbell curls&\exercise\cr
Triceps extensions&\exercise\cr
Squats&\exercise\cr
Deadlifts&\exercise\cr
Barbell rows&\exercise\cr
Lat pulldowns&\exercise\cr
Leg curls&\exercise\cr
Leg extensions&\exercise\cr
Crunches&\exercise
}

\vfill
