\include scripts/macros.script

\set hoffset 36
\set voffset 36
\set hsize 540
\set vsize 720

{\font nosifer 28 regular \centerline {The Gym Workout}}

\vskip 50

\centerline {Week of ___________}

\vskip 50

\set cgap 12
\set sgap 5

\def sets {____\hskip\sgap ____\hskip\sgap ____\hskip\sgap ____}
\def exercise {\sets&\sets&\sets}

\halign {
#\hskip\cgap\hfil&#\hskip\cgap\hfil&#\hskip\cgap\hfil&#\hfil\cr
&\hfil\underline{\hbox{\font noto 18 regular Monday}}&\hfil\underline{\hbox{\font noto 18 regular Wednesday}}&\hfil\underline{\hbox{\font noto 18 regular Friday}}\cr
\noalign{\vskip 18\underline{\hbox{\font noto 16 regular Chest/Arms/Shoulders}}\vskip 12}
Bench press&\exercise\cr
Peck deck&\exercise\cr
Overhead press&\exercise\cr
Bent-over raises&\exercise\cr
Barbell curls&\exercise\cr
Triceps extensions&\exercise\cr
\noalign{\vskip 18\underline{\hbox{\font noto 16 regular Legs/Back}}\vskip 12}
Squats&\exercise\cr
Deadlifts&\exercise\cr
Barbell rows&\exercise\cr
Lat pulldowns&\exercise\cr
Leg curls&\exercise\cr
Leg extensions&\exercise\cr
Crunches&\exercise
}

\vfill
